### ISSUE TITLE
Cannot find module '@yudiel/react-qr-scanner' or its corresponding type declarations.

### ISSUE THREAD

**Issue by invitatodev** [yudielcurbelo/react-qr-scanner#1]
### What?
Type declarations not working in Next.js 

### Dev Environment
- Next.js 12.2.4 with TypeScript
- node js v14.19.3
- MacOS

### Screenshot
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/106049860/185116444-c41d369c-e244-4cbc-b19f-1e5589163312.png">

**Comment by yudielcurbelo** [comment]
This issue is fixed in the new version. Please note that the import has changed to 
`import {QrScanner} from '@yudiel/react-qr-scanner';`

**Comment by invitatodev** [comment]
Working properly now. Thank you @yudielcurbelo !
<img width="875" alt="image" src="https://user-images.githubusercontent.com/106049860/185610758-deee2d5b-cea9-41d7-96fd-e3f037d13295.png">
