### ISSUE TITLE
How to close the QrScanner properly once we got the result ?

### ISSUE THREAD

**Issue by Santixay** [yudielcurbelo/react-qr-scanner#12]
I create a dialog component and put QrScanner in dialog content, when I get the result I would like to close the dialog also close the camera as well, but I got error when dialog is closing. 

I'm a newbie in React your help is much appreciated 

# Error message: 
Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0. 

# My source code
import {
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Typography,
} from "@mui/material";
import { QrScanner } from "@yudiel/react-qr-scanner";

function Scanner({ open, setOpen, onDecode }) {
  const handleClose = () => {
    setTimeout(() => setOpen(false), 0);
  };

  return (
    <Dialog fullScreen open={open} onClose={handleClose}>
      <DialogTitle id="alert-dialog-title">
        <Typography variant="">Scan Package by camera </Typography>
      </DialogTitle>
      <DialogContent
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <QrScanner
          onDecode={(result) => {
            if (result) {             
              onDecode(result);
              setOpen(false);
            }
          }}
          onError={(err) => {
            console.error(err?.message);
          }}
        />
      </DialogContent>
      <DialogActions>
        <Button
          variant="outlined"
          color="secondary"
          sx={{ px: 5 }}
          onClick={handleClose}
        >
          Close
        </Button>
      </DialogActions>
    </Dialog>
  );
}

export default Scanner;

**Comment by sofsscosta** [comment]
Having the same error, any help would be appreciated ⭐️

**Comment by mohamedamara1** [comment]
any updates on this?

**Comment by dulguuned** [comment]
import React, { useState } from 'react';
import QrScanner from 'react-qr-scanner';

const MyComponent = () => {
  const [scanning, setScanning] = useState(true);
  const [data, setData] = useState('');

  const handleScan = result => {
    if (result) {
      setData(result);
      setScanning(false); // This will cause the QrScanner component to not render after setting state
    }
  };

  const handleError = err => {
    console.error(err);
  };

  const scanner = scanning ? (
    <QrScanner
      delay={300}
      onError={handleError}
      onScan={handleScan}
      style={{ width: '100%' }}
    />
  ) : null;

  return (
    <div>
      {scanner}
      {data && <p>Result: {data}</p>}
    </div>
  );
};

export default MyComponent;
