### ISSUE TITLE
Camera Stream Continues After Modal Closure Due to Premature Unmount

### ISSUE THREAD

**Issue by 443781544** [yudielcurbelo/react-qr-scanner#15]
### Description
When using the scanner component inside a modal, if the modal is closed before the camera feed has fully initialized, the camera continues to run in the background. This issue seems to stem from a race condition where the clean-up function executes before the camera has been fully set up, leading to the stream not being properly stopped.

### Steps to reproduce
1. Open the modal which initializes the scanner component to start the camera stream.
2. Close the modal quickly before the camera feed fully initializes.
3. Notice that the camera light (if available on the device) remains on, indicating that the stream has not been stopped.

### Expected behavior
Closing the modal should also stop the camera stream completely, regardless of whether the camera has fully initialized or not.

### Actual behavior
The camera remains on even after the modal has been closed if the modal is closed before the camera feed is completely initialized.

**Comment by dulguuned** [comment]
import React, { useState } from 'react';
import QrScanner from 'react-qr-scanner';

const MyComponent = () => {
  const [scanning, setScanning] = useState(true);
  const [data, setData] = useState('');

  const handleScan = result => {
    if (result) {
      setData(result);
      setScanning(false); // This will cause the QrScanner component to not render after setting state
    }
  };

  const handleError = err => {
    console.error(err);
  };

  const scanner = scanning ? (
    <QrScanner
      delay={300}
      onError={handleError}
      onScan={handleScan}
      style={{ width: '100%' }}
    />
  ) : null;

  return (
    <div>
      {scanner}
      {data && <p>Result: {data}</p>}
    </div>
  );
};

export default MyComponent;

**Comment by HamadAbdullaBC** [comment]
Unfortunately even after the 1.2.0 release this issue is still there, even with the code snippet above.

**Comment by 443781544** [comment]
useEffect(() => {
        (async () => {
            await startDecoding();
        })();
        return () => {
            stopDecoding();
        };
    }, [startDecoding, stopDecoding]);

I think this is the code that causes the issue. Since startDecoding is async function, there's a chance that stopDecoding will run before it. In this case, the camera will not close properly and still run in the background even when the component is unmount.

**Comment by iamkevinhuang** [comment]
Hi, I experienced the same thing when using QrScanner over Modal from AntDesign. The way I fixed this was using the useEffect hook, I created 2 states, namely isScanning and modalIsOpen. So in my code function, when I want to disable QrScanner, I just use setIsScanning(false) then use useEffect for the callback to call setModalIsOpen(false).

useEffect(() => {
    setModalIsOpen(isScanning);
}, [isScanning]);

This method can fix the issue. I hope this helps!

**Comment by yudielcurbelo** [comment]
Sorry for taking so long to fix this issue. I just published version `1.2.1`. The issue should be fixed. Please verify and advise.

**Comment by 443781544** [comment]
thanks for the fix, the isMounted variable is causing issue in strictMode, can you change it to useRef?

**Comment by 443781544** [comment]
@yudielcurbelo 
```
  const isMounted = useRef(true);
  useEffect(() => {
    isMounted.current = true;

    (async () => {
      await startDecoding();

      if (!isMounted.current) {
        stopDecoding();
      }
    })();

    return () => {
      isMounted.current = false;
      stopDecoding();
    };
  }, [startDecoding, stopDecoding]);
```
