### ISSUE TITLE
Feature request - Pause reading

### ISSUE THREAD

**Issue by arxeiss** [yudielcurbelo/react-qr-scanner#17]
Thanks for your library, I'm trying to implement application to verify vouchers and it fits perfectly. But I'm missing one feature - pause reading.

Imagine scenario: 

1. Person at the entrance reads QR code and I send request to server. - *Here I would perform pause reading*
2. Waiting for server response about validity and details. - show details.
3. Show popup for lets say 5 seconds with details.
4. *Unpause reading*

I can do `videoElement.pause()` but which freeze the video. But then your app is constantly performing reading on that element. I know I can increase the `scanDelay`. But I would like to freeze it until timeout is gone or some click happen etc. And have possibility to pause reading instead of playing with `scanDelay` would be easier.

I want to perform pause to not send more request to server.

Thanks

**Comment by yudielcurbelo** [comment]
I just published `v1.2.3`. Now you have the option to pass a prop stopDecoding that is a boolean. Take a look at the demo. Hope this helps.

**Comment by arxeiss** [comment]
Thanks for very quick fix. It helps a lot.
