### ISSUE TITLE
What is the difference between onResult and onDecode?

### ISSUE THREAD

**Issue by Lermatroid** [yudielcurbelo/react-qr-scanner#19]
Thanks for the awesome library! I am using it atm and saw that there is a `onDecode` and `onResult`. I was wondering what the difference between the two is. Thanks!

**Comment by yudielcurbelo** [comment]
Both of them return the result. 

onResult: Scan event handler for result object.
onDecode: Scan event handler for decode value.

The difference is that onDecode will return the QrCode value as a text and onResult will return more data.
