### ISSUE TITLE
Select back camera

### ISSUE THREAD

**Issue by pbudnicki** [yudielcurbelo/react-qr-scanner#21]
Is it possible to select, which back camera should device use? In nowadays, a lot of mobile devices has more than one back camera, on Android this QR scanner selected my zoom camera, which has worst quality, instead of main back camera. I tested it in 2 devices, with the same result.

When I'm trying to fill in "deviceId" field with proper it, then it doesn't work.

**Comment by yudielcurbelo** [comment]
I have not tested it on any Android devices but for example on the iPhones the phone automatically switches cameras depending on the distance to the object.
