### ISSUE TITLE
it's not possible to set some of the constraints

### ISSUE THREAD

**Issue by nomaddan** [yudielcurbelo/react-qr-scanner#24]
I encountered an issue with certain Samsung devices (e.g. S22) where the camera fails to focus properly, resulting in blurry QR codes that cannot be scanned. Upon researching potential solutions on the internet, it appears that setting the auto-focus constraint `focusMode: continuous` may resolve the issue. Here's an example of how I try to use the constraints:

```jsx
constraints={{
  facingMode: 'environment',
  focusMode: 'continuous',
}}
```

However, when attempting to set the `focusMode` property, I encountered the following error:

```
Type '{ facingMode: string; focusMode: string; }' is not assignable to type 'MediaTrackConstraints'.
  Object literal may only specify known properties, and 'focusMode' does not exist in type 'MediaTrackConstraints'.
```

Upon inspecting the library source code, I observed that the `constraints` prop is passed to the `Finder` component and utilized in the `useMediaDevices` hook, as seen here: [useMediaDevices.ts](https://github.com/yudielcurbelo/react-qr-scanner/blob/main/src/hooks/useMediaDevices.ts).

Additionally, I noticed that there is an open issue (#22) on the repository regarding similar zoom constraint problem.

It seems logical to me that it should be possible to pass constraints such as `focusMode` or `zoom` to `window.navigator.mediaDevices`, especially when browser console output from `navigator.mediaDevices.getSupportedConstraints()` clearly states that those constraints do exist in the browser API.

Sources:
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#focusmode

https://forum.developer.samsung.com/t/camera-auto-focus-and-zoom-camera-not-working-in-the-web-application/27908/1

https://github.com/mebjas/html5-qrcode/issues/308

Besides that, it is a great library and works flawlessly on apple devices without any problems.

Kindly requesting @yudielcurbelo for any assistance or suggestions on how to address these issues.

**Comment by davidjandrey-sv** [comment]
I'm facing the same issue with focusMode apparently not being a property anymore. However the Scanner works flawlessly on Android phones for me (default config), and not at all on iPhones. Since you said that it works flawlessly on Apple devices, would you mind sharing your config? 😅

**Comment by cimicdk** [comment]
Were there any changes made in regards to this? I'm getting reports, only from Samsung phones, that their camera is not able to focus and the QR code that they are trying to scan is blurry. It seems to be solely from Samsung users, but I have not been able obtain more information about the browser etc.
I'm on 2.0.8 and I'm upgrading to the latest version (2.2.1) to try it out, but as far as I can see, nothing has changed in relation to this.

Have you heard anything more about this issue with samsung?
