### ISSUE TITLE
Module not found: Can't resolve '../assets/scanner-beep.mp3'

### ISSUE THREAD

**Issue by WynstelleID** [yudielcurbelo/react-qr-scanner#25]
When I build my project, there is an error like this.

<img width="451" alt="image" src="https://github.com/yudielcurbelo/react-qr-scanner/assets/58036512/21e05c3f-2cfc-45ec-b9e7-b3fff3b145ec">

**Comment by kosmokoks** [comment]
same :(

**Comment by yudielcurbelo** [comment]
I'm working on it.

**Comment by WynstelleID** [comment]
@yudielcurbelo @kosmokoks thanks for the solution

**Comment by yudielcurbelo** [comment]
Should be fixed in Version `1.2.10`. Please let me know.
