### ISSUE TITLE
This code creates issues when using without Vite

### ISSUE THREAD

**Issue by TNAJanssen** [yudielcurbelo/react-qr-scanner#28]
https://github.com/yudielcurbelo/react-qr-scanner/blame/6231aa2034b64fe864eab5182f5ce698ca97385f/src/hooks/useQrScanner.ts#L8

**Comment by yudielcurbelo** [comment]
This should be fixed in the beta version `2.0.0-beta.2`. Please note that there are also many changes in this version. Go over the README.
