### ISSUE TITLE
QR code not scanning

### ISSUE THREAD

**Issue by archer56** [yudielcurbelo/react-qr-scanner#3]
I have set this up in a little app and while most QR codes seem to work no problems, this one in the image and a few others don't seem to work. 
I get no errors, it's like it just doesn't recognise it as a QR code.

However, using an iPhone camera I get a URL to google drive from it for a restaurant menu, so it seems to be a valid QR code.
Do you have any ideas why it wouldn't work?

<img width="448" alt="image" src="https://user-images.githubusercontent.com/6969870/207050480-04a3bb01-6796-4bdd-8245-b871e01b4120.png">

**Comment by yudielcurbelo** [comment]
Not all grades of customization on the QR Codes are supported.
