### ISSUE TITLE
Lack of customisation for individual elements

### ISSUE THREAD

**Issue by alex-irvine** [yudielcurbelo/react-qr-scanner#39]
Add customisation prop to add in custom components for various elements. Most notably "Loading..." text to add matching loading icons/spinners/text as rest of site.

Can be extended to make it easier for other customisations not easy/possible with the CSS markers.

**Comment by hangryernest** [comment]
could we also get access to change the stroke color? 

<img width="650" alt="image" src="https://github.com/yudielcurbelo/react-qr-scanner/assets/82836089/7bbd1395-b747-4137-a1a2-78f6667a2a00">
