### ISSUE TITLE
bug:camera in browser keeps on scanning 

### ISSUE THREAD

**Issue by Rehankhalil462** [yudielcurbelo/react-qr-scanner#4]
In browser , camera keeps on scanning even if I unmount the component from react application. How to stop camera from scanning once it scans the qr code?

How can i switch off the camera , when i read the qrcode successfully? @idindrakusuma @yudielcurbelo

**Comment by yudielcurbelo** [comment]
Could you provide a code sandbox with the issue on hand?

After `QrScanner` is unmounted it will not exist anymore in the dom.

**Comment by Rehankhalil462** [comment]
By providing `tracker={false}` property to the QRScanner component, it solved the problem. Thanks for your fast reply.

**Comment by yoonh12** [comment]
> @yoonh12 yes. right. It keeps on scanning under the hood unless we refresh the browser or unmount the component. Or after successful scan, you can turn the camera off by just providing `tracker={false}` property in the QRScanner component.

I've already gave that prop but it didn't help.

**Comment by yudielcurbelo** [comment]
I'm not able to replicate this issue in Chrome or Safari. Could you provide an example with the issue?

**Comment by yoonh12** [comment]
> I'm not able to replicate this issue in Chrome or Safari. Could you provide an example with the issue?

I took a video and uploaded it on YouTube. Here's the link: [https://www.youtube.com/watch?v=D9boAG1DInY](https://www.youtube.com/watch?v=D9boAG1DInY)
(you should look at the webcam LED status on the laptop. It doesn't turn off even after I go back. And the QrScanner is actually working at that moment.)

**Comment by palat-inc** [comment]
The bug is reproduced. QrScanner component doesn't present in DOM, but camera is still working. tracker={false} doesn't affect anything.

**Comment by yoonh12** [comment]
> The bug is reproduced. QrScanner component doesn't present in DOM, but camera is still working. tracker={false} doesn't affect anything.

Yes. I really want to fix this bug. but I don't know how :(

**Comment by raghupviyer** [comment]
Can you add a button for start and stop scanning or give us an api to implement it, to start the camera and stop it whenever we require it ... check out [html5-qrcode](https://blog.minhazav.dev/research/html5-qrcode), this could stop  the issue

**Comment by raghupviyer** [comment]
Check this pull request out, it solves the issue

**Comment by sojib-lowp** [comment]
I am getting this console error on unmount of `QRScanner` container component.
```
DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at e2.makeBufferFromCanvasImageData (http://192.168.68.110:3000/node_modules/.vite/deps/@yudiel_react-qr-scanner.js?v=687bf47f:1354:34)
    at new e2 (http://192.168.68.110:3000/node_modules/.vite/deps/@yudiel_react-qr-scanner.js?v=687bf47f:1351:72)
    at t2.createBinaryBitmap (http://192.168.68.110:3000/node_modules/.vite/deps/@yudiel_react-qr-scanner.js?v=687bf47f:1877:46)
    at t2.decode (http://192.168.68.110:3000/node_modules/.vite/deps/@yudiel_react-qr-scanner.js?v=687bf47f:1873:19)
    at n2 (http://192.168.68.110:3000/node_modules/.vite/deps/@yudiel_react-qr-scanner.js?v=687bf47f:1865:23)
```
Just before this error I also get some warnings like this:
```
BrowserCodeReader.js:527 It was not possible to play the video.
```
and
```
BrowserCodeReader.js:515 Trying to play video that is already playing.
```

**Comment by yudielcurbelo** [comment]
Could you try it using 'localhost' or 'https'. By your error I see that you are using http.

**Comment by dlogvin** [comment]
Same issue here. The camera doesn't stop. I saw in the story that there is a button that actually makes the camera stop, but I cannot find that button on the code. Any help?

**Comment by dorklord23** [comment]
I use version 2.3.1 and the bug still persists even after unmounting the component
