### ISSUE TITLE
 useDeviceList() throws error when no cameras are available

### ISSUE THREAD

**Issue by MarcoWel** [yudielcurbelo/react-qr-scanner#40]
On a computer without cameras, the line
`const cameraDevices = useDeviceList();`
causes an uncaught runtime error "Requested device not found".
IMO this should just create an empty array [].

**Comment by yudielcurbelo** [comment]
Please try this beta `2.0.0-beta.8`. There are breaking changes for this beta release.

**Comment by yudielcurbelo** [comment]
This issue is fixed on new hook `useDevices`.
