### ISSUE TITLE
Camera loading in ionic react-app

### ISSUE THREAD

**Issue by kyleh27** [yudielcurbelo/react-qr-scanner#43]
when I try to use the scanner in an ionic react app for my android phone, the app runs fine on my laptop webapp and the camera opens, but whenever I build in android studio and try to launch the app on my android device it just shows a big triangle play icon and the word loading 
![Screenshot_20240521-105851_camera-scanner](https://github.com/yudielcurbelo/react-qr-scanner/assets/47543119/c6c92da8-5d34-4586-9b96-f59278233329)

**Comment by yudielcurbelo** [comment]
I'm not sure about Ionic, but you could try the new beta and let me know `2.0.0-beta.8`.

**Comment by kyleh27** [comment]
I got it to work after restarting my pc and android device (idk why), but thank you for the quick reply. Also there is no QrScanner exported in the beta versions and I wanted to use the onDecode so I'm using the 1.2.10 version. For starting and stopping the scanner

**Comment by yudielcurbelo** [comment]
The `onDecode` was removed for `onScan`. `onScan` return an array, since now is possible to scan multiple QR Codes at the same time. If you only one Qr Code, just get the first element of it. You can try the beta, it is faster and has a much smaller package size.

**Comment by kyleh27** [comment]
am I doing this wrong? because this is what i get when I treat it as an array 
![image](https://github.com/yudielcurbelo/react-qr-scanner/assets/47543119/d0be7c2e-4a30-4e28-906f-047605f7fed9)
![image](https://github.com/yudielcurbelo/react-qr-scanner/assets/47543119/dbf8e302-3658-4c49-b7ad-6ad8edfecd9f)

**Comment by yudielcurbelo** [comment]
This is the type that is returned

```typescript
export interface IDetectedBarcode {
    boundingBox: IBoundingBox;
    cornerPoints: IPoint[];
    format: string;
    rawValue: string;
}
```

You should use `rawValue` instead of `text`.
