### ISSUE TITLE
How to use the useContinuousScanner

### ISSUE THREAD

**Issue by Abe101** [yudielcurbelo/react-qr-scanner#45]
I mainly want to create a custom scanner since most of your components are not customizable but with the same functionality as it has. I found this hook but I do not understand how to use it. Any example would help immensely.

**Comment by yudielcurbelo** [comment]
You could use the `Scanner` component to accomplish this.

```typescript
<Scanner
  formats={["qr_code"]}
  onScan={(detectedCodes) => console.log(detectedCodes)}
  components={{
    finder: false,
  }}
  allowMultiple={true}
>
  <p>Custom stuff</p>
</Scanner>;
```

Set the finder component to false and implement your custom logic for the UI.

You could also look at the code in the `Finder` component, to see how it was done.

**Comment by Abe101** [comment]
But what about the hook? What is it used for? I thought I could use it to create my own scanner components
