### ISSUE TITLE
Scanner is not working in android apps

### ISSUE THREAD

**Issue by sudheer-h** [yudielcurbelo/react-qr-scanner#46]
when I try to use the scanner in android app for my android phone, the app runs fine on my laptop webapp and the camera opens, but whenever I open it in android app I am getting blank screen  I have also tried your new version 2.0.0-beta but still not working attaching the screenshot  below
![Screenshot_20240527-111119_Teams](https://github.com/yudielcurbelo/react-qr-scanner/assets/119580496/c11f0ad3-702b-45c6-ba80-4d6e21534ae5)

**Comment by yudielcurbelo** [comment]
> when I try to use the scanner in android app for my android phone, the app runs fine on my laptop webapp and the camera opens, but whenever I open it in android app I am getting blank screen  I have also tried your new version 2.0.0-beta but still not working attaching the screenshot  below
> 
> ![Screenshot_20240527-111119_Teams](https://github.com/yudielcurbelo/react-qr-scanner/assets/119580496/c11f0ad3-702b-45c6-ba80-4d6e21534ae5)
> 
> 
> 
> 

Are you on localhost or https?

**Comment by sudheer-h** [comment]
I am running it in a app which is already deployed and available globally

**Comment by hastalavistababy** [comment]
Have you granted camera permission?
