### ISSUE TITLE
Can not turn on/off browser's camera by using setState

### ISSUE THREAD

**Issue by vanthao-github** [yudielcurbelo/react-qr-scanner#47]
Sorry, but I don't know how to turn the browser's camera off/on using setState. I could do it in version 1.2.10, but it seems unstable. Sometimes I can turn off the camera, but sometimes I can't.

**Comment by BrunoTeixeiraNDB** [comment]
In the new version presented, it is possible to access in the following way

`import {
	Scanner, boundingBox,
} from "@yudiel/react-qr-scanner";`

`const [enabled, setEnabled] = useState(false);`

`<Scanner
							onScan={handleScanWebCam}
							paused={enabled}
							constraints={{facingMode: cameraFacingMode}}
							components={{
								audio: false,
								onOff: false, // the onOff controls the scanner
								torch: false,
								tracker: getTracker()
							}}
						/>`

At least that's what I understand until now when the official documentation isn't out. rsrs...

**Comment by vanthao-github** [comment]
Thank for replied @BrunoTeixeiraNDB , let me try your method. Thanks again!

**Comment by yudielcurbelo** [comment]
If what you want is to start with the camera off, you could try to pass `false` to the `pause` prop. Please let me know.
