### ISSUE TITLE
ERROR: Failed to execute 'detect' on BarcodeDetector': Barcode detection service unavailable

### ISSUE THREAD

**Issue by BrunoTeixeiraNDB** [yudielcurbelo/react-qr-scanner#48]
When trying to open the camera on a Galaxy TAB A8 tablet and received this error 'ERROR: Failed to execute 'detect' on BarcodeDetector': Barcode detection service unavailable'
, I've already tried to look for solutions for contouring, but without success, I'm only using it to read QRCodes but it says it doesn't have access to barcodes, how do I make it only stay on QRCodes?

Thank you for your attention and I am available if you need me.
![ERROR](https://github.com/yudielcurbelo/react-qr-scanner/assets/84329066/d0b92ab6-fb22-4c16-8577-7a5d8a5197d3)

**Comment by yudielcurbelo** [comment]
You can use the `formats` props to filter what barcodes to scan.

```typescript
formats={[
    'qr_code',
    'micro_qr_code',
    'rm_qr_code',
    'maxi_code',
    'pdf417',
    'aztec',
    'data_matrix',
    'matrix_codes',
    'dx_film_edge',
    'databar',
    'databar_expanded',
    'codabar',
    'code_39',
    'code_93',
    'code_128',
    'ean_8',
    'ean_13',
    'itf',
    'linear_codes',
    'upc_a',
    'upc_e'
]}
```

**Comment by testerslol123** [comment]
Thank you for the answer, @yudielcurbelo .
If can, would you update the README at frontpage? I believe some people will confused at why it cannot scan code_128 barcode :)

**Comment by yudielcurbelo** [comment]
> Thank you for the answer, @yudielcurbelo . If can, would you update the README at frontpage? I believe some people will confused at why it cannot scan code_128 barcode :)

Was the issue resolved?

**Comment by BrunoTeixeiraNDB** [comment]
Thank you @yudielcurbelo.
 the problem still persists, I'm trying to carry out some more tests to determine what causes this error on an Android tablet, although it works on Android cell phones normally.

**Comment by BrunoTeixeiraNDB** [comment]
Hi, While checking what could be happening, I identified this error below.
![error](https://github.com/yudielcurbelo/react-qr-scanner/assets/84329066/056363ce-2a9d-4bc6-8793-226d854988fe)

**Comment by yudielcurbelo** [comment]
> Hi, While checking what could be happening, I identified this error below. ![error](https://private-user-images.githubusercontent.com/84329066/335194448-056363ce-2a9d-4bc6-8793-226d854988fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTY3OTYsIm5iZiI6MTcxNzE1NjQ5NiwicGF0aCI6Ii84NDMyOTA2Ni8zMzUxOTQ0NDgtMDU2MzYzY2UtMmE5ZC00YmM2LTg3OTMtMjI2ZDg1NDk4OGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDExNTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMWFmZTZhNDk1ZDZiNjY0MmY4MTYwZjdiYTgxNzYyZDhkNmQwNWIzMjRiYzdjNGUwMzAyNTUxOWQ0ODg1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xgRwojlw-InIkw86gB8MM9615i2ZffjSKQH_k_mOS_o)



> Hi, While checking what could be happening, I identified this error below. ![error](https://private-user-images.githubusercontent.com/84329066/335194448-056363ce-2a9d-4bc6-8793-226d854988fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTY3OTYsIm5iZiI6MTcxNzE1NjQ5NiwicGF0aCI6Ii84NDMyOTA2Ni8zMzUxOTQ0NDgtMDU2MzYzY2UtMmE5ZC00YmM2LTg3OTMtMjI2ZDg1NDk4OGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDExNTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMWFmZTZhNDk1ZDZiNjY0MmY4MTYwZjdiYTgxNzYyZDhkNmQwNWIzMjRiYzdjNGUwMzAyNTUxOWQ0ODg1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xgRwojlw-InIkw86gB8MM9615i2ZffjSKQH_k_mOS_o)

By any chance are you using tablet as an internal tool without internet access?

**Comment by BrunoTeixeiraNDB** [comment]
Correct, I have the tablet on a separate network where it has limited access, if this is the case, what links are necessary for me to be able to release it to correct this problem?

**Comment by yudielcurbelo** [comment]
> Correct, I have the tablet on a separate network where it has limited access, if this is the case, what links are necessary for me to be able to release it to correct this problem?

Make sure that is able to make this request `https://fastly.jsdelivr.net/npm/zxing-wasm@1.2.10/dist/reader/zxing_reader.wasm`

**Comment by BrunoTeixeiraNDB** [comment]
Thanks!! I managed to do it after releasing the request.

**Comment by BrunoTeixeiraNDB** [comment]
Thanks!! I managed to do it after releasing the request.

**Comment by RodargDev** [comment]
Is there any way for me to use the library in an offline environment? I get that the url should be available but what if it isn't? couldn't you include the wasm in the build instead of requesting it? this would also add offline support for websites if it were the case

**Comment by hossamelshamyy** [comment]
> Is there any way for me to use the library in an offline environment? I get that the url should be available but what if it isn't? couldn't you include the wasm in the build instead of requesting it? this would also add offline support for websites if it were the case

@RodargDev This will help you
https://github.com/yudielcurbelo/react-qr-scanner/issues/81#issuecomment-2343842018
