### ISSUE TITLE
Failed to parse source map from warnings

### ISSUE THREAD

**Issue by floriscornel** [yudielcurbelo/react-qr-scanner#5]
Thanks for building and maintaining this library. 
I'm getting source map warnings when running react-scripts start (CRA).

react version: 18.2.0
react-qr-scanner version: 1.1.4

```
Failed to parse source map from '/usr/src/app/node_modules/@yudiel/src/components/Counter.tsx' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/@yudiel/src/components/Counter.tsx'

Failed to parse source map from '/usr/src/app/node_modules/@yudiel/src/components/Finder.tsx' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/@yudiel/src/components/Finder.tsx'

Failed to parse source map from '/usr/src/app/node_modules/@yudiel/src/components/QrScanner.tsx' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/@yudiel/src/components/QrScanner.tsx'

...
```

**Comment by yudielcurbelo** [comment]
Are you able to see this folder structure in your node_modules?

![image](https://user-images.githubusercontent.com/15385920/226596858-29228c9d-f32a-441c-b907-57021cdbc505.png)

**Comment by yudielcurbelo** [comment]
If the warning persists, please update to `1.1.5` and let me know.

**Comment by floriscornel** [comment]
@yudielcurbelo Thanks for your quick reply.
I have updated to `1.1.5`, but I am still experiencing this problem.


I have found that the warning mentions:
`node_modules/@yudiel/react-qr-scanner/src/utilities/isObject.ts`
On my disk I can find:
`node_modules/@yudiel/react-qr-scanner/dist/cjs/utilities/isObject.d.ts`
and
`node_modules/@yudiel/react-qr-scanner/dist/esm/utilities/isObject.d.ts`

<img width="1148" alt="Screenshot 2023-03-22 at 09 32 42" src="https://user-images.githubusercontent.com/65155757/226862693-6b5158dd-0bb8-4412-8880-40b4a965389c.png">

**Comment by yudielcurbelo** [comment]
What version of node are you using, could you delete the node_modules folder and reinstall all dependencies?

**Comment by floriscornel** [comment]
I am running `v19.8.1` on macOS, encountered the same problem using docker image `node:18.12.1-alpine`.

I tried deleting node_modules and reinstalling, without success.

I have created a repo to help you reproduce the issue:
https://github.com/floriscornel/example-qr

Running commands:
`npm install` and `npm start`, for me, results in:
```
...
WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/floriscornel/Developer/example-qr/node_modules/@yudiel/react-qr-scanner/src/utilities/off.ts' file: Error: ENOENT: no such file or directory, open '/Users/floriscornel/Developer/example-qr/node_modules/@yudiel/react-qr-scanner/src/utilities/off.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/floriscornel/Developer/example-qr/node_modules/@yudiel/react-qr-scanner/src/utilities/on.ts' file: Error: ENOENT: no such file or directory, open '/Users/floriscornel/Developer/example-qr/node_modules/@yudiel/react-qr-scanner/src/utilities/on.ts'

webpack compiled with 14 warnings
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
No issues found.
```

**Comment by yudielcurbelo** [comment]
This is something specific to CRA #https://github.com/mswjs/msw/issues/1030#issue-1081147782

I do not distribute the src file in the library, but doing so should fix the issue. I will give it a try.

**Comment by floriscornel** [comment]
@yudielcurbelo Thank you.
I have confirmed that the warnings are no longer present after updating to version `1.1.6`.

**Comment by Havock94** [comment]
I updated react-qr-scanner from `1.1.9` to `1.2.10` and the warnings reappeared. Going back to version `1.1.9` "solves" the problem.

**Comment by yudielcurbelo** [comment]
There is a new beta `2.0.0-beta.8` with a lot of changes. If the issue is not fixed here, I can add the src folder to the build output.

**Comment by tvriya** [comment]
I'm getting this error in the latest version `2.0.8`. Is there any solution for that?
