### ISSUE TITLE
Allow versions < React 18 as peer dependency

### ISSUE THREAD

**Issue by eimerreis** [yudielcurbelo/react-qr-scanner#50]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@yudiel/react-qr-scanner@2.0.1` for the project I'm working on.

I am using this package in scope of a react 17 based project. From what I saw across the repo, the package does not actively use any React 18 features.  

Couldn't we open the peer dependency version range to allow other versions than react 18? 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@yudiel/react-qr-scanner/package.json b/node_modules/@yudiel/react-qr-scanner/package.json
index c2c824d..f897269 100644
--- a/node_modules/@yudiel/react-qr-scanner/package.json
+++ b/node_modules/@yudiel/react-qr-scanner/package.json
@@ -55,7 +55,7 @@
     "typescript": "^5.4.5"
   },
   "peerDependencies": {
-    "react": "^18.2.0",
+    "react": "^17.0.0 || ^18.2.0",
     "react-dom": "^18.2.0"
   },
   "dependencies": {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by eimerreis** [comment]
Sorry, forgot to add `react-dom` as well

**Comment by yudielcurbelo** [comment]
Could this work for you?

```json
 "peerDependencies": {
    "react": "^17 || ^18",
    "react-dom": "^17 || ^18"
  }
```

**Comment by eimerreis** [comment]
yeah would work 👍

**Comment by eimerreis** [comment]
@yudielcurbelo works! 🙂 Big up for the superfast response & fix
