### ISSUE TITLE
Permissions on Safari are asked everytime 

### ISSUE THREAD

**Issue by Abe101** [yudielcurbelo/react-qr-scanner#51]
If I use the scanner on safari it asks permissions for camera. But the next time I open the scanner again it again asks for permissions. Is there a way for me to handle the permissions myself or if once permissions are given then don't ask again?

**Comment by yudielcurbelo** [comment]
> If I use the scanner on safari it asks permissions for camera. But the next time I open the scanner again it again asks for permissions. Is there a way for me to handle the permissions myself or if once permissions are given then don't ask again?

That is safari implementation. Please watch video. https://github.com/yudielcurbelo/react-qr-scanner/assets/15385920/2b7a6d37-baff-43c0-b090-ad0acfb680b6
