### ISSUE TITLE
It is not possible to open the camera on an Asus notebook, cannot find its information

### ISSUE THREAD

**Issue by BrunoTeixeiraNDB** [yudielcurbelo/react-qr-scanner#52]
![image_2024_06_07T19_18_16_125Z](https://github.com/yudielcurbelo/react-qr-scanner/assets/84329066/1c35cf9d-7269-47f4-a9e1-6fef0a0baf14)

**Comment by yudielcurbelo** [comment]
> ![image_2024_06_07T19_18_16_125Z](https://github.com/yudielcurbelo/react-qr-scanner/assets/84329066/1c35cf9d-7269-47f4-a9e1-6fef0a0baf14)
> 
> 

Could you go here [link(https://yudielcurbelo.github.io/react-qr-scanner/?path=/story/devices--devices)](https://yudielcurbelo.github.io/react-qr-scanner/?path=/story/devices--devices) and provide the output.

**Comment by hacKarim** [comment]
[
  {
    "deviceId": "",
    "kind": "videoinput",
    "label": "",
    "groupId": ""
  }
]

**Comment by BrunoTeixeiraNDB** [comment]
I tried to perform the test by modifying the width and height using constraints, but it didn't work as expected.

**Comment by BrunoTeixeiraNDB** [comment]
I carried out the test and the camera actually doesn't open even in the link you indicated...

**Comment by BrunoTeixeiraNDB** [comment]
I apologize to @hacKarim , increasing the size of width and height solved the problem, I appreciate your help!
