### ISSUE TITLE
Camera Zoom

### ISSUE THREAD

**Issue by ArtlookAgency** [yudielcurbelo/react-qr-scanner#53]
I'm having problems with small barcodes. Is there a way to 2x zoom the camera?

**Comment by yudielcurbelo** [comment]
You could use the `constraints` prop for that.

For example:

```tsx
constraints={{
    advanced: [
        {
            zoom: 2
        }
    ]
}}
```

**Comment by yudielcurbelo** [comment]
Please check the new version `2.0.3`, I just included a zoom component.

**Comment by ArtlookAgency** [comment]
thank you
