### ISSUE TITLE
onError not supported anymore?

### ISSUE THREAD

**Issue by stx-odeveci** [yudielcurbelo/react-qr-scanner#54]
I wanted to ask how to catch errors in the latest 2.0.2 version, as an onError callback is not passed anymore. Thanks in advance!

**Comment by yudielcurbelo** [comment]
The scanner will not throw any error, if the barcode cannot be scanned it will simply ignore it.

**Comment by stx-odeveci** [comment]
Yes, but how can we catch the Errors while the Camera gets mounted, for example if camera access is blocked?

**Comment by osmandvc** [comment]
Hi @yudielcurbelo, I need to handle these errors, thats why i locally implemented the onError callback and i thought maybe you want to include it in the package itself. Opened the PR #58  for it.

**Comment by osmandvc** [comment]
Hi @yudielcurbelo, I need to handle these errors, thats why i locally implemented the onError callback and i thought maybe you want to include it in the package itself. Opened the PR #59 for it.

**Comment by Donkie** [comment]
I need this too, +1

**Comment by nickdee1** [comment]
Hello, @yudielcurbelo. Any updates regarding this issue? This feature is highly needed 🙏

**Comment by yudielcurbelo** [comment]
It is now back in the latest version.
