### ISSUE TITLE
Possibility for video to go full height

### ISSUE THREAD

**Issue by mutheusalmeida** [yudielcurbelo/react-qr-scanner#57]
Hey, Yudiel! Congrats on the amazing work you're doing with this library. I struggled a lot to find one as good as yours.

But I have a question. Is it possible for the user camera cover the full height of the device and do not show any white borders? Thanks in advance!

**Comment by yudielcurbelo** [comment]
> Hey, Yudiel! Congrats on the amazing work you're doing with this library. I struggled a lot to find one as good as yours.
> 
> 
> 
> But I have a question. Is it possible for the user camera cover the full height of the device and do not show any white borders? Thanks in advance!

Do you mean this border? ![image](https://github.com/yudielcurbelo/react-qr-scanner/assets/15385920/0fca85e4-b343-46c4-ba22-b18c115e1a6e)

**Comment by yudielcurbelo** [comment]
I just merge some changes that will allow you to add classNames to the container and video element. Please use version `2.0.4`.

**Comment by mutheusalmeida** [comment]
> I just merge some changes that will allow you to add classNames to the container and video element. Please use version `2.0.4`.

I mean this:

![2024-06-14_19-37](https://github.com/yudielcurbelo/react-qr-scanner/assets/34585988/65dd07c5-ce37-4f6b-8964-68b49334e181)

This solves the problem:
![2024-06-14_22-29](https://github.com/yudielcurbelo/react-qr-scanner/assets/34585988/63f23ede-e451-4fdd-9c60-ca1d1013bf17)

**Comment by dias19** [comment]
> > I just merge some changes that will allow you to add classNames to the container and video element. Please use version `2.0.4`.
> 
> I mean this:
> 
> ![2024-06-14_19-37](https://private-user-images.githubusercontent.com/34585988/339949145-65dd07c5-ce37-4f6b-8964-68b49334e181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjEzOTksIm5iZiI6MTcyMzYyMTA5OSwicGF0aCI6Ii8zNDU4NTk4OC8zMzk5NDkxNDUtNjVkZDA3YzUtY2UzNy00ZjZiLTg5NjQtNjhiNDkzMzRlMTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA3MzgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NGVkZjcxNDE3YTZiNzU5ZmNlZTZiNmIxNzA3MmQ3NTdiY2E0YzRiYzU5ZmQyYjAwMjRlOTFhMzdhODE2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wdmToKTmjVseOCKq8_IbJyMWhugLxjtKOquq6ATItvE)
> 
> This solves the problem: ![2024-06-14_22-29](https://private-user-images.githubusercontent.com/34585988/339949143-63f23ede-e451-4fdd-9c60-ca1d1013bf17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjEzOTksIm5iZiI6MTcyMzYyMTA5OSwicGF0aCI6Ii8zNDU4NTk4OC8zMzk5NDkxNDMtNjNmMjNlZGUtZTQ1MS00ZmRkLTljNjAtY2ExZDEwMTNiZjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA3MzgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNzE4MzRmZGIzYmVjMDFmN2NkMGMyNWFmMWNhZDZhZjJkMGIyZWFlM2RmZmFjZDdiM2FhOWRiZjE0Y2RhYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1TX7VBP3Fle-HkRXJxaDQdUAwqXlENkGrsexB1xQ6mA)

Hey, I encountered the same problem with styling the Scanner component, i was able to set the video to full screen, but unable to style the borders to be in the center like in the screen you shared (I have similar design). I do have similar design, but currently unable to style the red borders, were you able to achieve the desired design?

**Comment by MarcusPOliveira** [comment]
> > > I just merge some changes that will allow you to add classNames to the container and video element. Please use version `2.0.4`.
> > 
> > 
> > I mean this:
> > ![2024-06-14_19-37](https://private-user-images.githubusercontent.com/34585988/339949145-65dd07c5-ce37-4f6b-8964-68b49334e181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjEzOTksIm5iZiI6MTcyMzYyMTA5OSwicGF0aCI6Ii8zNDU4NTk4OC8zMzk5NDkxNDUtNjVkZDA3YzUtY2UzNy00ZjZiLTg5NjQtNjhiNDkzMzRlMTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA3MzgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NGVkZjcxNDE3YTZiNzU5ZmNlZTZiNmIxNzA3MmQ3NTdiY2E0YzRiYzU5ZmQyYjAwMjRlOTFhMzdhODE2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wdmToKTmjVseOCKq8_IbJyMWhugLxjtKOquq6ATItvE)
> > This solves the problem: ![2024-06-14_22-29](https://private-user-images.githubusercontent.com/34585988/339949143-63f23ede-e451-4fdd-9c60-ca1d1013bf17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjEzOTksIm5iZiI6MTcyMzYyMTA5OSwicGF0aCI6Ii8zNDU4NTk4OC8zMzk5NDkxNDMtNjNmMjNlZGUtZTQ1MS00ZmRkLTljNjAtY2ExZDEwMTNiZjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA3MzgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNzE4MzRmZGIzYmVjMDFmN2NkMGMyNWFmMWNhZDZhZjJkMGIyZWFlM2RmZmFjZDdiM2FhOWRiZjE0Y2RhYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1TX7VBP3Fle-HkRXJxaDQdUAwqXlENkGrsexB1xQ6mA)
> 
> Hey, I encountered the same problem with styling the Scanner component, i was able to set the video to full screen, but unable to style the borders to be in the center like in the screen you shared (I have similar design). I do have similar design, but currently unable to style the red borders, were you able to achieve the desired design?

Hello @dias19, did you solve this?
