### ISSUE TITLE
"Could not start video source" error on Android 7 and Chrome 109

### ISSUE THREAD

**Issue by jswiton** [yudielcurbelo/react-qr-scanner#6]
Hey, first of all, thank you for this lib, it's awesome.
Unfornutelly I found one glitch. When I run [Storybook demo](https://yudielcurbelo.github.io/react-qr-scanner/?path=/story/qr-scanner--scan-code) on the Android 7 and Chrome 109.0.5414 video is not starting. Instead, I see the `"Could not start video source"` error.
Seems like [this](https://github.com/yudielcurbelo/react-qr-scanner/blob/5e41ecc9de1e8f480d3f69fd97d4521c28213711/stories/QrScanner.stories.tsx#L27) is called for some reason.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/4461343/228345562-326e65ba-b4c6-45c5-95e4-cf868af56295.png">

I have the same issue in my react app using your library. On Android 8 it works well.
This Android device can run camera video (check other websites to test if it's device related issue).

Is there a chance to look at it from your side? Thank you in advance!

**Comment by yudielcurbelo** [comment]
Could you send me the output of [Media Device List](https://yudielcurbelo.github.io/react-qr-scanner/?path=/story/media-device--list-devices). This will give me a better idea of the camera on that device.
