### ISSUE TITLE
Camera blank when I request the permission for the first time.

### ISSUE THREAD

**Issue by phantodev** [yudielcurbelo/react-qr-scanner#65]
Friends... I have the following problem... I request permission to access the camera... and I give permission. When I try to access the component the camera goes blank. If I press F5 and refresh my screen, my camera reloads normally. Does anyone know what can it be?

**Comment by alamenai** [comment]
Hi @phantodev , please could you share your device, browser ... to reproduce it?

**Comment by dominictobias** [comment]
How do you request permission? on latest iOS and latest Safari and Chrome it never asks for permissions and is just blank. Maybe worth noting I am on HTTP (not S)
