### ISSUE TITLE
List of cameras doesn't work when permission is set to "Ask"

### ISSUE THREAD

**Issue by JamesCrawley** [yudielcurbelo/react-qr-scanner#70]
## **Issue**:
The `useDevices` hook doesn't return the full list of cameras when browser permission is set to "Ask" rather than "Allow"

## **Expected:** 
The `useDevices` hook should return the full list of cameras as soon as the user grants camera permission to the browser

## **When Safari' s camera permission is set to "Ask"**

```
[
    {
        "deviceId": "",
        "kind": "videoinput",
        "label": "",
        "groupId": ""
    }
]
```
Note: `Camera 1` here is fallback text provided by me
<img src="https://github.com/user-attachments/assets/c7d2ede4-06a1-42fc-95fc-c7c3b19815f6" width="50%">

## When Safari's camera permission is set to "Allow"
<img src="https://github.com/user-attachments/assets/f6c88a9d-f2c2-4723-ba47-ded7c9e71aa4" width="50%">

**Comment by RossyBundeva** [comment]
I have the same isue for all browsers on windows

**Comment by JOSBALIN** [comment]
Pinging this issue.
