### ISSUE TITLE
Scanner window on initial display incorrect size

### ISSUE THREAD

**Issue by dbrody2004** [yudielcurbelo/react-qr-scanner#71]
I have the scanner component inside the dialog box.  The dialog box has the wrong dimensions when there is no camera image in it and cuts off the scanner component.  When there is an image everything works fine.  This is the case with any React component such as Box, Card, etc
<img width="480" alt="Screenshot 2024-08-07 at 5 10 10 PM" src="https://github.com/user-attachments/assets/7080f6db-2464-44e9-b069-a5b995d3af2b">
<img width="517" alt="Screenshot 2024-08-07 at 5 09 59 PM" src="https://github.com/user-attachments/assets/65957291-a9d1-4a40-b6e6-4a7b2dc45d14">

**Comment by ahansson89** [comment]
Were you able to solve this?

**Comment by ahansson89** [comment]
I fixed it with these styles:
```styles={{
            container: {
              width: "100%",
              height: "0", // hack to make the video not shift the layout
              paddingBottom: "100%", // hack to make the video not shift the layout
            },
            video: { width: "100%", height: "auto" }, // hack to make the video not shift the layout
          }}```
