### ISSUE TITLE
Facing issue while scanning QR in Different browser and different OS

### ISSUE THREAD

**Issue by rohitpote000** [yudielcurbelo/react-qr-scanner#76]
iphone 
a) Chrome and Safari : 1st attempt back camera is on and able to scan small size QR code
but attempt to scan 2nd attempt onward front camera is on and cannot turn to back camera , i need to close whole browser and re do then only switch to back camera.
b) Google : passed - every attempt is back-camera and able to scan small size QR code.

android
a) Chrome : camera cannot on at all.
b) Google : 1st attempt can on back-camera, but cannot scan small size QR code. 2nd attempts onwards camera is not on at all. just showing white blank screen.

**Comment by raishudesu** [comment]
i get similar problem

{
    "name": "NotReadableError",
    "message": "Could not start video source"
}
