### ISSUE TITLE
ENOENT Warnings

### ISSUE THREAD

**Issue by SpeamNiklas** [yudielcurbelo/react-qr-scanner#79]
i've installed the package with npm but i get these ENOENT warnings. Do you know a way to solve this?

Using Version 2.0.7

------------------------------------------------------------------------------------------------------------------------------------------

`WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\CameraOff.tsx' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\CameraOff.tsx'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\CameraOn.tsx' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\CameraOn.tsx'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\TorchOff.tsx' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\TorchOff.tsx'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\TorchOn.tsx' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\TorchOn.tsx'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\ZoomIn.tsx' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\ZoomIn.tsx'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\ZoomOut.tsx' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\ZoomOut.tsx'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\base64Beep.ts' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\assets\base64Beep.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\components\Finder.tsx' file: Error: ENOENT: no such 
file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\components\Finder.tsx'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\components\OnOff.tsx' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\components\OnOff.tsx'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\components\Scanner.tsx' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\components\Scanner.tsx'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\components\Torch.tsx' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\components\Torch.tsx'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\components\Zoom.tsx' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\components\Zoom.tsx'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\hooks\useCamera.ts' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\hooks\useCamera.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\hooks\useDevices.ts' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\hooks\useDevices.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\hooks\useScanner.ts' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\hooks\useScanner.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\misc\defaultComponents.ts' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\misc\defaultComponents.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\misc\defaultConstraints.ts' file: Error: ENOENT: no 
such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\misc\defaultConstraints.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\misc\defaultStyles.ts' file: Error: ENOENT: no such 
file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\misc\defaultStyles.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\misc\overlays.ts' file: Error: ENOENT: no such file 
or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\misc\overlays.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\misc\shimGetUserMedia.ts' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\misc\shimGetUserMedia.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\deepEqual.ts' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\deepEqual.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\idempotent.ts' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\idempotent.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\isDateObject.ts' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\isDateObject.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\isNullOrUndefined.ts' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\isNullOrUndefined.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\isObject.ts' file: Error: ENOENT: no such 
file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\isObject.ts'

WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\isPrimitive.ts' file: Error: ENOENT: no such file or directory, open 'P:\Test_Project\node_modules\@yudiel\react-qr-scanner\src\utilities\isPrimitive.ts'`

**Comment by charlesfayal** [comment]
Seeing this as well with the latest version

**Comment by tvriya** [comment]
@charlesfayal Did you find any solution?

**Comment by SpeamNiklas** [comment]
> Which platform do you use (Next.js etc.)? I don't have this problem using Next.js 14.2.14

Using React 18.2.0

**Comment by micheleangelofabbri** [comment]
I'm on React v18.3.1 and seeing the same warning messages on a debian v12 box with react-qr-scanner v2.0.8. The software seems to be functioning fine for my purposes though.

**Comment by BenGWeeks** [comment]
I am also seeing this with a `create-react-app` solution.

```
WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\.....\GitHub\Zapp.ie\tabs\node_modules\@yudiel\react-qr-scanner\src\utilities\isPrimitive.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\.....\GitHub\Zapp.ie\tabs\node_modules\@yudiel\react-qr-scanner\src\utilities\isPrimitive.ts'
```

There is no `src` folder in `C:\Users\...\GitHub\Zapp.ie\tabs\node_modules\@yudiel\react-qr-scanner`.

**Comment by yitzgold** [comment]
I am also getting the same warnings using `CRA`.

`WARNING in ./node_modules/@yudiel/react-qr-scanner/dist/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/node_modules/@yudiel/react-qr-scanner/src/assets/CameraOff.tsx' file: Error: ENOENT: no such file or directory, open '/node_modules/@yudiel/react-qr-scanner/src/assets/CameraOff.tsx'`

**Comment by BrunoTeixeiraNDB** [comment]
I am also getting the same warnings  with React v17.

**Comment by SpeamNiklas** [comment]
Error this exists, should not be marked as completed...

**Comment by micheleangelofabbri** [comment]
> Error still exists, should not be marked as completed...

I am also still running into the same error.
