### ISSUE TITLE
Is there any way for me to use the library in an offline environment?

### ISSUE THREAD

**Issue by tiziodcaio** [yudielcurbelo/react-qr-scanner#81]
Is there any way for me to use the library in an offline environment? I get that the url should be available but what if it isn't? couldn't you include the wasm in the build instead of requesting it? this would also add offline support for websites if it were the case

_Originally posted by @RodargDev in https://github.com/yudielcurbelo/react-qr-scanner/issues/48#issuecomment-2203011502_
            
We now have the same issue. Is there any way of fixing it?

**Comment by hossamelshamyy** [comment]
Good point, I will make a PR for it

**Comment by Tarikjrh** [comment]
> The library already exports `setZXingModuleOverrides`, which you can provide it with your local copy of the .wasm file, as explained in the following link https://github.com/Sec-ant/barcode-detector#:~:text=In%20addition%20to,%7D)%3B
> 
> You can follow the following steps:
> 
> 1. Download the .wasm file from this link https://fastly.jsdelivr.net/npm/zxing-wasm@1.2.12/dist/reader/zxing_reader.wasm
> 2. Place the file in any folder, Ex public dir
> 3. In the same code file you are using the qr scanner add the following snippet
> 
> ```js
> import { Scanner, setZXingModuleOverrides } from '@yudiel/react-qr-scanner';
> import wasmFile from "/zxing_reader.wasm?url"; //edit the path if it is not placed in the public dir
> 
> const Component = () => {
>     setZXingModuleOverrides({
>         locateFile: (path, prefix) => {
>           if (path.endsWith(".wasm")) {
>             return wasmFile;
>           }
>           return prefix + path;
>         },
>       });
> // rest of your code
> }
> ```
if anyone is struggling to get this working,make sure to use the latest version of the .wasm file.
as of my comment version 1.3.4 is the latest
ex: https://fastly.jsdelivr.net/npm/zxing-wasm@1.3.4/dist/reader/zxing_reader.wasm
