### ISSUE TITLE
Failed to start another camera instance when a user selects a camera that is not working e.g OBS virtual camera

### ISSUE THREAD

**Issue by techwithtwin** [yudielcurbelo/react-qr-scanner#85]
![image](https://github.com/user-attachments/assets/47f2806a-895b-4bbc-b95a-29b680fabd45)

When a user selects a camera on the dropdown and then useing the device ID in the constrains it gives an error, could not start video source, but then when a user selects another camera that was working the camera is not loaded and everything is like blank

video explanation of the bug!
https://www.loom.com/share/c74773cab6724369972623e4353ad1d3?sid=f4f7eabe-d1ae-40d0-99dd-1631b264a3e6

**Comment by mammutserver** [comment]
Which Browser do you use?

**Comment by techwithtwin** [comment]
Chrome ✅
