### ISSUE TITLE
Failed to open stream in Firefox browser

### ISSUE THREAD

**Issue by arjunanda** [yudielcurbelo/react-qr-scanner#86]
This is the error I received:

MediaStreamError { 
  name: "OverconstrainedError", 
  message: "Constraints could not be satisfied.", 
  constraint: "height", 
  stack: "" 
}

![image](https://github.com/user-attachments/assets/6ec46653-d483-4049-8fff-18b1167297be)

**Comment by nolife08021** [comment]
@arjunanda i facing same issue, may i know how did you solve it?
