### ISSUE TITLE
The caméra is not working on PWA for the qr scanner

### ISSUE THREAD

**Issue by dido2007** [yudielcurbelo/react-qr-scanner#88]

**Comment by IlyaBelousov** [comment]
same

**Comment by PushHandle** [comment]
same

**Comment by PushHandle** [comment]
more specifically - it scans, beeps, captures an empty object...

`
0
: 
{boundingBox: DOMRectReadOnly, rawValue: '', format: 'unknown', cornerPoints: Array(4)}
length
: 
1
[[Prototype]]
: 
Array(0)`

**Comment by PushHandle** [comment]
However, I do see that the demo is capturing the object correctly...
https://yudielcurbelo.github.io/react-qr-scanner/?path=/story/scanner--scanner

**Comment by PushHandle** [comment]
@martinmorenoc worth noting that I found it works perfectly well in the demo: https://yudielcurbelo.github.io/react-qr-scanner/?path=/story/scanner--scanner

**Comment by martinmorenoc** [comment]
In the meantime, I resolved the issue by disabling the sound and adding a check at the start of the `onScan` callback to ensure the `rawValue` is not empty before processing the scanned code.

If you’d like to add sound, you can use something like [use-sound](https://www.npmjs.com/package/use-sound) when the code is valid.

**Comment by mohitgangwani** [comment]
For me, nothing is getting scanned, I tried multiple times. Though the demo code works perfectly.

**Comment by selmaheric** [comment]
> same here, it is scanning codes with `unknown` format and empty `rawValue`.
> 
> even when I have only `qr_code` in the formats prop.
> 
> ```
> [
>     {
>         "boundingBox": {
>             "x": 0,
>             "y": 0,
>             "width": 0,
>             "height": 0,
>             "top": 0,
>             "right": 0,
>             "bottom": 0,
>             "left": 0
>         },
>         "rawValue": "",
>         "format": "unknown",
>         "cornerPoints": [
>             {
>                 "x": 0,
>                 "y": 0
>             },
>             {
>                 "x": 0,
>                 "y": 0
>             },
>             {
>                 "x": 0,
>                 "y": 0
>             },
>             {
>                 "x": 0,
>                 "y": 0
>             }
>         ]
>     }
> ]
> ```

I am also getting this. Sometimes it reads the real value, sometimes it just reads an empty string with unknown format. Also tried setting up formats property but that didn't work

**Comment by martinmorenoc** [comment]
any solutions on this
