### ISSUE TITLE
Flip the camera preview image when needed

### ISSUE THREAD

**Issue by JanMisker** [yudielcurbelo/react-qr-scanner#9]
It would be great if the video element with the camera preview shows the image 'flipped' if the camera is facing the user. That way left&right make more sense, e.g. when on a laptop and you're holding up a QR code you can easier put it inside the view.

From my quick research:
- On desktop (laptop) browsers every camera can point somewhere else, but I suppose it's safe to assume it faces the user. I think it **does not** return a `facingMode` in `stream.getVideoTracks[0].getCapabilities()`.
- On mobile browser it seems you can get the `facingMode` from `stream.getVideoTracks[0].getCapabilities()`.

So perhaps the video preview should be flipped always, unless `stream.getVideoTracks[0].getCapabilities().facingMode === 'environment'` ?

A video can be flipped by applying this style: `{ transform: scaleX(-1); }`.

I can create a PR for this, but maybe you have certain reasons to not implement it?

**Comment by yudielcurbelo** [comment]
Sounds like a good idea to me.
